language: python
sudo: false
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6-dev
    - pypy
install:
    - pip install tox coveralls
script:
    - tox -e py
after_success:
    - coveralls
notifications:
    email: false
